### PR TITLE
Rework: metadata and documents

### PR DESCRIPTION
**Pull request by donvipre**
- Fix: LICENSE.md to LICENSE
- Update: README.md
- Update: docs
- Rework: tests

## Reference
 - Resolves: #8

### CODE REVIEW

**Review by dschier-wtd — CHANGES_REQUESTED** [review]
Found some smaller issues:
- travis.yml should be aligned to skeleton (that seems to be the reason of teh failing tests)
- it should role.svg (was an error in the skeleton, fixed with the last merge)
```
[![Build Status](https://travis-ci.org/while-true-do/ansible-role-repo-mariadbsvg?branch=master)](https://travis-ci.org/while-true-do/ansible-role-repo-mariadb) 
```
Everything else looks awesome.

**Comment by daniel-schier** [comment]
you should add the words:
MariaDB
gpg


to .aspell

and change Repo to Repository ;)

**Comment by donvipre** [comment]
the role should be "Repository-MariaDB"?

**Comment by daniel-schier** [comment]
sometimes the little things take the longest ^^

**Review by dschier-wtd — APPROVED** [review]

**Comment by daniel-schier** [comment]
when tests are ok, you can merge. from my side nothing to find :)

**Pull request merged**
